name: Profile README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "39 3 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: 'Create env file'
        run: |
            echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install Dependencies
        run: npm install
      - name: Install ts-node
        run: npm install -g ts-node typescript '@types/node'
      - name: Rebuild README.md File
        run: |-
            ts-node src/app.ts "$GH_TOKEN" "$OPENAI_API_KEY"
      - name: Commit and Push if Changed
        run: |-
          git add .
          git diff
          git config --global user.email "your.email@here.com"
          git config --global user.name "coolprofiles-bot"
          git commit -m "docs: auto-update README.md" -a || exit 0
          git push